language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: ej8k9ZY7A7tazg/zgQLoNrRzxnc46Mi99zuPkkDcy/vP0tJwyF0TYCd+B9EjIPr+8QKb6y3eJVbRgTgUnv2+oBTyJR+gaAet/LVyRW98hua3XL2ynPXEIcSNMXaolbxOb+sERuFvbEnDdjtTza3ir5yVOh9S8QPvAbKiMyek6D2dXlixJSSuNdtY6HCA//YT7z52+nFN171J5uWfQkXNJJV34/hXURehsyzJ8MihrcTe3MK9kCVp5zsHQgROwh0qmfxRVBYsJVHsIGihBJRy5Cy2noPhd54k7nsLdOCuUKjHs9VudktEjpW6CifaFfEN8vJqtHsdH4xWdmfUiYJ6fKf8ISTZsxxaBce+vBNPgYgbdjlDtxCvJVySaUjYjDzrf/CUoljWU5zfXQ3uDv4jq5V/ZoJEk92VqVTfJACXJjtVHQmWI8tRUrsGIdgskjCFbGAC0oVUblLUQmMHFr8HcQOi8PV5ex1oKywDRMb9lGBBTVE9WQhruG7iu7TCe1c57sT2qygZ+E5odEF7grcj48L9UgtxbFhJs3zZq7MWuDZIV3lamvvVklnIi6cSss2j5Lj1kDNQEHLFXr2jL6rEsfdeKgKMUDoxlKl9BifXkXTwqp/XlFOQZHxYJrlMfD5tIFU1Do5wTF+m3ztiEOCy1hz76dDWYlYhKzCE9gDbgGw=
  - secure: pcITehwq7PtqaRR3z4/4jkBB2sx8PJvb1DornscozGb2xrajgN1nXW6NECZkZk8Zmmfa4nzUnuJHyu8kdqx5OmY0xj5ypvVinFIqAAjaTQY+gISmiodDeSbsJeeR26cFNV0fpEQq+h/rTBpiTNI8+0Gx/DCxZAC8SlznRVM8dcGJD6rlHyf3Lk9mPdtj1vqhQlsSPpNF+Zi9bdQynYSgkCw2J3q1ULsk9n27gPNVCKS5DNRcC/D7DB0QFMj7/Z7mAF2ZQKFDTaz05QYgkBTnO3PibSkiWRIvMUJRHVz62UGw5bCaPCm526DU4LAA+HBosN8gN/+SwVFD9KlFaniD2g5aVF78V6bUq4WQ+U+RwdRUWR1GWKjkEUn7erYnIU0kwl6ZhxCHeqjzoFUe4EPdOMW6ASQy+J17GcmApRIZC1vgL1jGRqH2gBLULYQ3Awpv+gx6QTOAQxfVEfWz6jaXJ5+RiWJb7hiOVJMeuXsfG7Ca6oC9T7UtebVarPBTl2yO7e5EpociYt+YdUa0S4q1GiX2aMvCuGhebZYyzRtYJaHlRY4IrkKtQesOJPwtE1gDJexME4LgsT56oc+SURNM7pr7BOip4IwVVqCsBTFcUo/PnelijbnCR8V5dpkBDSI2SHsUDgBVubX+R5u/nl+s4Rk7H6s7kzqA/1aB5R6sxF0=
